### PR TITLE
Adding Amazigh main layout and somn edits to kabyle

### PR DESCRIPTION
**Pull request by abdelhaqueidali**
Amazigh layout was added
Mapping.yaml was updated
Kabyle loyut was edited by rearranging some letters and removing one not used in kabyle

### CODE REVIEW

**Comment by tenextractor** [comment]
The Kabyle layout has been added by another user @BoFFire, is it a good idea to change it?

**Comment by BoFFire** [comment]
@abdelhaqueidali @tenextractor Hi,
Not a good idea to change the kabyle layout. I'm planning to introduce a new variant of the kabyle layout supporting 4 rows as discussed before.

Please check CLDR for kabyle alphabet as it is standardized : https://www.unicode.org/cldr/charts/46/summary/kab.html

The kabyle merged layout was discussed with our translation community that is active on a lot of projects such as Mozilla, Gnome, Fedora, Debian etc.

If you have any question about Kabyle language we will be happy to answer.

Regards.

**Comment by Akselyan** [comment]
I am a kabyle développer and localizator for many years, it's not good idea at all. Please refer to to the official kabyle alphabet in CLDR: https://www.unicode.org/cldr/charts/46/summary/kab.html

**Comment by abdelhaqueidali** [comment]
> The Kabyle layout has been added by another user @BoFFire, is it a good idea to change it?

I did not change the layout, I just modified it.
seeing the changes and discussing them is what is required in case you are not sure about applying the change.

**Comment by abdelhaqueidali** [comment]
> @abdelhaqueidali @tenextractor Hi, Not a good idea to change the kabyle layout. I'm planning to introduce a new variant of the kabyle layout supporting 4 rows as discussed before.
> 
> Please check CLDR for kabyle alphabet as it is standardized : https://www.unicode.org/cldr/charts/46/summary/kab.html
> 
> The kabyle merged layout was discussed with our translation community that is active on a lot of projects such as Mozilla, Gnome, Fedora, Debian etc.
> 
> If you have any question about Kabyle language we will be happy to answer.
> 
> Regards.


I want to know why is ɛ is in a. they are not similar.
usually ɛ is in the position of ɣ where ɣ is located now.
ɣ is usually where v is located now.
f should give v as b gives p when long press.
also some letters have variants which some use, maybe these varaints are not needed to be added in this case.

**Comment by abdelhaqueidali** [comment]
> @abdelhaqueidali @tenextractor Hi, Not a good idea to change the kabyle layout. I'm planning to introduce a new variant of the kabyle layout supporting 4 rows as discussed before.
> 
> Please check CLDR for kabyle alphabet as it is standardized : https://www.unicode.org/cldr/charts/46/summary/kab.html
> 
> The kabyle merged layout was discussed with our translation community that is active on a lot of projects such as Mozilla, Gnome, Fedora, Debian etc.
> 
> If you have any question about Kabyle language we will be happy to answer.
> 
> Regards.


seeing

> The Kabyle layout has been added by another user @BoFFire, is it a good idea to change it?

seeing
https://github.com/futo-org/futo-keyboard-layouts/pull/100#issuecomment-2495505972

I think I am going to add Moroccan Amazigh (Latin) zgh-latn
and add it to it.

**Comment by abdelhaqueidali** [comment]
> The Kabyle layout has been added by another user @BoFFire, is it a good idea to change it?

Is it possible to accept only Amazigh layout that was added, ow rhould I do something and pull request again?

**Comment by tenextractor** [comment]
> Is it possible to accept only Amazigh layout that was added, or should I do something and pull request again?

You can revert the changes to the Kabyle layout and commit to the same branch.

**Pull request closed without merging**
