### PR TITLE
Fix Tamil and Kannada layouts

### PR DESCRIPTION
**Pull request by tenextractor**
Current layouts for some Indian languages are defective, see https://github.com/Helium314/HeliBoard/issues/900 for more information. This PR fixes the layouts for Tamil and Kannada. Marathi, Telugu and Malayalam are still affected and will be fixed in another PR.

These are only temporary fixes until it is possible to get context-dependent "smart" IMEs working on FUTO Keyboard.

### CODE REVIEW

**Comment by abb128** [comment]
Introducing significant changes to existing layouts should be avoided to avoid interfering with existing users ability to type if they're already used to those layouts, maybe make them separate?

**Comment by tenextractor** [comment]
I don't think it is *possible* to get used to these layouts. For example, the existing Kannada layout literally does not have the vowel 'o', so it is impossible to type Kannada with that layout anyway. And imagine if the English layout had capital letters by default and you have to long press to write the small ones, no one would use such a layout. In my opinion these layouts should be replaced.

But if you *really* want to keep them, please don't make them the default.

**Comment by abb128** [comment]
The default is just whichever one's the top for a language in mapping.yaml, so you can just make new yaml files and put them at the top for those languages

**Comment by tenextractor** [comment]
Added old as well as new layouts.

**Comment by abb128** [comment]
Please keep the old ones named as they were. The keyboard will look for a `kannada` layout for existing users and since it's no longer there it'll break

**Comment by tenextractor** [comment]
Do I need to change the names inside the YAML too?

**Pull request merged**
